#APPLICATION BROWSER
browser=chrome
#APPLICATION URL
url=https://www.demoblaze.com
#APPLICATION LOGIN CREDENTIALS
username=Divya Yugesh
password=automation

name=Divya Yugesh
country=India
city=Chennai
card=1234 3456 6789 8909
month=September
year=2026